In [56]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from streamlit import columns

In [57]:
data = pd.read_excel('transport_data.xlsx')
data

,ДАТА,КУРС_ДАТА,ВЪЗЛОЖИТЕЛ,КУРС,МАРШРУТ_СНИМКА,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,...,ТОЛ_РАЗХОДИ,ЗАРЕДЕНО_ГОРИВО,ДРУГИ_РАЗХОДИ,СЪЗДАТЕЛ,СЪЗДАДЕНО_НА,ПРОМЯНА_ОТ,ПОСЛЕДЕН_ЪПДЕЙТ,ГОДИНА,МЕСЕЦ,ДЕН
0,20260127-0001,2026-01-26,ОФИС ВАРНА,Русе-Тервел-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 07:48:35.139,Plamen Svetoslavov,2026-04-01 18:48:15.743,2026,1,27
1,20260127-0002,2026-01-27,ОФИС ВАРНА,Варна-Риш-Нефтохим,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 16:36:41.699,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,27
2,20260127-0003,2026-01-28,ОФИС ВАРНА,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 16:39:22.266,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,27
3,20260128-0001,2026-01-29,ОФИС ВАРНА,Варна-Шабла-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-28 15:39:15.844,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,28
4,20260129-0001,2026-01-30,ОФИС ВАРНА,Варна-НХК-Повеляново-Добрич-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-29 11:09:16.459,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,20260401-0008,2026-02-13,ОФИС ВАРНА,Бяла-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,CB2201CC,P2849EE,50.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-04-01 10:46:49.509,Plamen Svetoslavov,2026-04-01 18:46:19.556,2026,4,1
89,20260401-0009,2026-02-17,ОФИС ВАРНА,Русе-Павликени-Ловеч-д.Луковит-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,CB2201CC,P2849EE,440.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-04-01 10:48:25.015,Plamen Svetoslavov,2026-04-01 18:46:19.556,2026,4,1
90,20260401-0010,2026-02-23,ОФИС ВАРНА,Русе-Плевен-София,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,320.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-04-01 11:07:48.212,Plamen Svetoslavov,2026-04-01 18:46:19.556,2026,4,1
91,20260401-0011,2026-02-24,ОФИС ВАРНА,София-Радомир-Плевен,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,270.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-04-01 11:11:48.883,Plamen Svetoslavov,2026-04-01 18:46:19.556,2026,4,1
92,20260401-0012,2026-02-25,ОФИС ВАРНА,Плевен-Хасково-Любимец-Поморие-Ахелой-Каблешко...,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,850.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-04-01 11:14:02.026,Plamen Svetoslavov,2026-04-01 18:46:19.556,2026,4,1

In [58]:
cleaned_data = data[['СЪЗДАТЕЛ', 'ВЪЗЛОЖИТЕЛ', 'КУРС_ДАТА', 'КУРС', 'ПРЕВОЗВАЧ', 'ШОФЬОР', 'ВЛЕКАЧ', 'ЦИСТЕРНА', 'КМ', 'Л', '€_ЦЕНА_ОБЩО', '€_ЦЕНА_ЗА_1000', 'ДЕН', 'МЕСЕЦ', 'ГОДИНА']]
cleaned_data = cleaned_data.rename(columns={'СЪЗДАТЕЛ': 'ТЪРГОВЕЦ'})
cleaned_data

,ТЪРГОВЕЦ,ВЪЗЛОЖИТЕЛ,КУРС_ДАТА,КУРС,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА
0,Vesela Nikolova,ОФИС ВАРНА,2026-01-26,Русе-Тервел-Русе,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026
1,Vesela Nikolova,ОФИС ВАРНА,2026-01-27,Варна-Риш-Нефтохим,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026
2,Vesela Nikolova,ОФИС ВАРНА,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026
3,Vesela Nikolova,ОФИС ВАРНА,2026-01-29,Варна-Шабла-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026
4,Vesela Nikolova,ОФИС ВАРНА,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Vesela Nikolova,ОФИС ВАРНА,2026-02-13,Бяла-Русе,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,CB2201CC,P2849EE,50.0,20000,150.0,7.500000,1,4,2026
89,Vesela Nikolova,ОФИС ВАРНА,2026-02-17,Русе-Павликени-Ловеч-д.Луковит-Русе,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,CB2201CC,P2849EE,440.0,29000,460.0,15.862069,1,4,2026
90,Vesela Nikolova,ОФИС ВАРНА,2026-02-23,Русе-Плевен-София,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,320.0,24000,320.0,13.333333,1,4,2026
91,Vesela Nikolova,ОФИС ВАРНА,2026-02-24,София-Радомир-Плевен,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,270.0,22000,120.0,5.454545,1,4,2026
92,Vesela Nikolova,ОФИС ВАРНА,2026-02-25,Плевен-Хасково-Любимец-Поморие-Ахелой-Каблешко...,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,850.0,30000,1000.0,33.333333,1,4,2026

In [59]:
cleaned_data['courses_points'] = cleaned_data['КУРС'].apply(lambda x: x.split('-'))
cleaned_data['points_count'] = cleaned_data['courses_points'].apply(lambda x: len(x) - 2)
cleaned_data = cleaned_data[['ТЪРГОВЕЦ', 'ВЪЗЛОЖИТЕЛ', 'КУРС_ДАТА', 'КУРС', 'points_count', 'ПРЕВОЗВАЧ', 'ШОФЬОР', 'ВЛЕКАЧ', 'ЦИСТЕРНА', 'КМ', 'Л', '€_ЦЕНА_ОБЩО', '€_ЦЕНА_ЗА_1000', 'ДЕН', 'МЕСЕЦ', 'ГОДИНА']]
cleaned_data = cleaned_data.rename(columns={'points_count': 'БРОЙ_ОБЕКТИ'})
cleaned_data

,ТЪРГОВЕЦ,ВЪЗЛОЖИТЕЛ,КУРС_ДАТА,КУРС,БРОЙ_ОБЕКТИ,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА
0,Vesela Nikolova,ОФИС ВАРНА,2026-01-26,Русе-Тервел-Русе,1,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026
1,Vesela Nikolova,ОФИС ВАРНА,2026-01-27,Варна-Риш-Нефтохим,1,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026
2,Vesela Nikolova,ОФИС ВАРНА,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,4,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026
3,Vesela Nikolova,ОФИС ВАРНА,2026-01-29,Варна-Шабла-Варна,1,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026
4,Vesela Nikolova,ОФИС ВАРНА,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,3,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Vesela Nikolova,ОФИС ВАРНА,2026-02-13,Бяла-Русе,0,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,CB2201CC,P2849EE,50.0,20000,150.0,7.500000,1,4,2026
89,Vesela Nikolova,ОФИС ВАРНА,2026-02-17,Русе-Павликени-Ловеч-д.Луковит-Русе,3,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,CB2201CC,P2849EE,440.0,29000,460.0,15.862069,1,4,2026
90,Vesela Nikolova,ОФИС ВАРНА,2026-02-23,Русе-Плевен-София,1,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,320.0,24000,320.0,13.333333,1,4,2026
91,Vesela Nikolova,ОФИС ВАРНА,2026-02-24,София-Радомир-Плевен,1,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,270.0,22000,120.0,5.454545,1,4,2026
92,Vesela Nikolova,ОФИС ВАРНА,2026-02-25,Плевен-Хасково-Любимец-Поморие-Ахелой-Каблешко...,6,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,850.0,30000,1000.0,33.333333,1,4,2026

In [60]:
cleaned_data.to_csv('transport_data.csv', index=False)

In [61]:
cleaned_data = pd.read_csv('transport_data.csv')
cleaned_data

,ТЪРГОВЕЦ,ВЪЗЛОЖИТЕЛ,КУРС_ДАТА,КУРС,БРОЙ_ОБЕКТИ,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА
0,Vesela Nikolova,ОФИС ВАРНА,2026-01-26,Русе-Тервел-Русе,1,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026
1,Vesela Nikolova,ОФИС ВАРНА,2026-01-27,Варна-Риш-Нефтохим,1,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026
2,Vesela Nikolova,ОФИС ВАРНА,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,4,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026
3,Vesela Nikolova,ОФИС ВАРНА,2026-01-29,Варна-Шабла-Варна,1,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026
4,Vesela Nikolova,ОФИС ВАРНА,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,3,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Vesela Nikolova,ОФИС ВАРНА,2026-02-13,Бяла-Русе,0,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,CB2201CC,P2849EE,50.0,20000,150.0,7.500000,1,4,2026
89,Vesela Nikolova,ОФИС ВАРНА,2026-02-17,Русе-Павликени-Ловеч-д.Луковит-Русе,3,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,CB2201CC,P2849EE,440.0,29000,460.0,15.862069,1,4,2026
90,Vesela Nikolova,ОФИС ВАРНА,2026-02-23,Русе-Плевен-София,1,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,320.0,24000,320.0,13.333333,1,4,2026
91,Vesela Nikolova,ОФИС ВАРНА,2026-02-24,София-Радомир-Плевен,1,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,270.0,22000,120.0,5.454545,1,4,2026
92,Vesela Nikolova,ОФИС ВАРНА,2026-02-25,Плевен-Хасково-Любимец-Поморие-Ахелой-Каблешко...,6,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,850.0,30000,1000.0,33.333333,1,4,2026

In [62]:
mean_km = round(cleaned_data['КМ'].mean(), 2)
mean_liters = round(cleaned_data['Л'].mean(), 2)
mean_price_total = round(cleaned_data['€_ЦЕНА_ОБЩО'].mean(), 2)
mean_price_per_1000 = round(cleaned_data['€_ЦЕНА_ЗА_1000'].mean(), 2)
mean_price_per_1000

np.float64(12.83)