In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from streamlit import columns

In [2]:
data = pd.read_excel('transport_data.xlsx')
data

,ДАТА,КУРС_ДАТА,ВЪЗЛОЖИТЕЛ,КУРС,БРОЙ_ОБЕКТИ,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,...,ТОЛ_РАЗХОДИ,ЗАРЕДЕНО_ГОРИВО,ДРУГИ_РАЗХОДИ,СЪЗДАТЕЛ,СЪЗДАДЕНО_НА,ПРОМЯНА_ОТ,ПОСЛЕДЕН_ЪПДЕЙТ,ГОДИНА,МЕСЕЦ,ДЕН
0,20260127-0001,2026-01-26,ОФИС ВАРНА,Русе-Тервел-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 07:48:35.139,Plamen Svetoslavov,2026-04-01 18:48:15.743,2026,1,27
1,20260127-0002,2026-01-27,ОФИС ВАРНА,Варна-Риш-Нефтохим,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 16:36:41.699,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,27
2,20260127-0003,2026-01-28,ОФИС ВАРНА,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 16:39:22.266,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,27
3,20260128-0001,2026-01-29,ОФИС ВАРНА,Варна-Шабла-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-28 15:39:15.844,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,28
4,20260129-0001,2026-01-30,ОФИС ВАРНА,Варна-НХК-Повеляново-Добрич-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-29 11:09:16.459,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,20260828-0003,2026-08-28,ОФИС ВАРНА,Бяла-Варна-Добрич-Русе,3.0,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,NaN,NaN,470.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-08-28 15:04:33.635,Vesela Nikolova,2026-08-28 15:08:47.823,2026,8,28
304,20260828-0004,2026-08-28,ОФИС ВАРНА,Бяла-Варна-Добрич-Тервел-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ВЕНЦИСЛАВ КРУМОВ,NaN,NaN,500.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-08-28 15:08:51.932,Vesela Nikolova,2026-08-28 15:10:27.840,2026,8,28
305,20260828-0005,2026-08-31,ОФИС ВАРНА,Варна-НХК-Каварна-Добрич-Варна,6.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,NaN,NaN,500.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-08-28 15:10:31.826,Vesela Nikolova,2026-08-28 15:15:27.312,2026,8,28
306,20260828-0006,2026-08-31,ОФИС ВАРНА,Русе-Тервел-Нова Камена - Гешаново-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,NaN,NaN,440.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-08-28 15:15:32.192,Vesela Nikolova,2026-08-28 15:19:50.228,2026,8,28
307,20260831-0001,2026-08-31,ОФИС ВАРНА,НХК-Поморие,1.0,ДЪЛВАН ЕООД,ИВАН ГЕОРГИЕВ ТУРМАНОВ,А7660КР,NaN,NaN,...,NaN,NaN,NaN,Vesela Nikolova,2026-08-31 15:47:19.892,Vesela Nikolova,2026-08-31 15:49:09.969,2026,8,31

In [3]:
data.columns

Index(['ДАТА', 'КУРС_ДАТА', 'ВЪЗЛОЖИТЕЛ', 'КУРС', 'БРОЙ_ОБЕКТИ', 'ПРЕВОЗВАЧ',
       'ШОФЬОР', 'ВЛЕКАЧ', 'ЦИСТЕРНА', 'КМ', 'Л', '€_ЦЕНА_ОБЩО',
       '€_ЦЕНА_ЗА_1000', 'ЛИТРИ_1', 'СТАТУС_ФАКТУРА', 'ЛИТРИ_2', 'ТОЛ_РАЗХОДИ',
       'ЗАРЕДЕНО_ГОРИВО', 'ДРУГИ_РАЗХОДИ', 'СЪЗДАТЕЛ', 'СЪЗДАДЕНО_НА',
       'ПРОМЯНА_ОТ', 'ПОСЛЕДЕН_ЪПДЕЙТ', 'ГОДИНА', 'МЕСЕЦ', 'ДЕН'],
      dtype='object')

In [4]:
cleaned_data = data[['СЪЗДАТЕЛ', 'ВЪЗЛОЖИТЕЛ', 'КУРС_ДАТА', 'КУРС', 'БРОЙ_ОБЕКТИ', 'ПРЕВОЗВАЧ', 'ШОФЬОР', 'ВЛЕКАЧ', 'ЦИСТЕРНА', 'КМ', 'Л', '€_ЦЕНА_ОБЩО', '€_ЦЕНА_ЗА_1000', 'ДЕН', 'МЕСЕЦ', 'ГОДИНА', 'ЛИТРИ_1', 'ЛИТРИ_2']]
cleaned_data = cleaned_data.rename(columns={'СЪЗДАТЕЛ': 'ТЪРГОВЕЦ'})
cleaned_data

,ТЪРГОВЕЦ,ВЪЗЛОЖИТЕЛ,КУРС_ДАТА,КУРС,БРОЙ_ОБЕКТИ,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА,ЛИТРИ_1,ЛИТРИ_2
0,Vesela Nikolova,ОФИС ВАРНА,2026-01-26,Русе-Тервел-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026,NaN,NaN
1,Vesela Nikolova,ОФИС ВАРНА,2026-01-27,Варна-Риш-Нефтохим,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026,NaN,NaN
2,Vesela Nikolova,ОФИС ВАРНА,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026,NaN,NaN
3,Vesela Nikolova,ОФИС ВАРНА,2026-01-29,Варна-Шабла-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026,NaN,NaN
4,Vesela Nikolova,ОФИС ВАРНА,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,Vesela Nikolova,ОФИС ВАРНА,2026-08-28,Бяла-Варна-Добрич-Русе,3.0,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,NaN,NaN,470.0,32000,564.0,17.625000,28,8,2026,NaN,20000.0
304,Vesela Nikolova,ОФИС ВАРНА,2026-08-28,Бяла-Варна-Добрич-Тервел-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ВЕНЦИСЛАВ КРУМОВ,NaN,NaN,500.0,20000,550.0,27.500000,28,8,2026,NaN,7000.0
305,Vesela Nikolova,ОФИС ВАРНА,2026-08-31,Варна-НХК-Каварна-Добрич-Варна,6.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,NaN,NaN,500.0,32000,600.0,18.750000,28,8,2026,12000.0,16000.0
306,Vesela Nikolova,ОФИС ВАРНА,2026-08-31,Русе-Тервел-Нова Камена - Гешаново-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,NaN,NaN,440.0,32000,528.0,16.500000,28,8,2026,NaN,32000.0
307,Vesela Nikolova,ОФИС ВАРНА,2026-08-31,НХК-Поморие,1.0,ДЪЛВАН ЕООД,ИВАН ГЕОРГИЕВ ТУРМАНОВ,А7660КР,NaN,NaN,8000,NaN,0.000000,31,8,2026,NaN,8000.0

In [5]:
cleaned_data = cleaned_data[['ТЪРГОВЕЦ', 'ВЪЗЛОЖИТЕЛ', 'КУРС_ДАТА', 'КУРС', 'БРОЙ_ОБЕКТИ', 'ПРЕВОЗВАЧ', 'ШОФЬОР', 'ВЛЕКАЧ', 'ЦИСТЕРНА', 'КМ', 'Л', '€_ЦЕНА_ОБЩО', '€_ЦЕНА_ЗА_1000', 'ДЕН', 'МЕСЕЦ', 'ГОДИНА', 'ЛИТРИ_1', 'ЛИТРИ_2']]
cleaned_data = cleaned_data.rename(columns={'points_count': 'БРОЙ_ОБЕКТИ'})
cleaned_data

,ТЪРГОВЕЦ,ВЪЗЛОЖИТЕЛ,КУРС_ДАТА,КУРС,БРОЙ_ОБЕКТИ,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА,ЛИТРИ_1,ЛИТРИ_2
0,Vesela Nikolova,ОФИС ВАРНА,2026-01-26,Русе-Тервел-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026,NaN,NaN
1,Vesela Nikolova,ОФИС ВАРНА,2026-01-27,Варна-Риш-Нефтохим,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026,NaN,NaN
2,Vesela Nikolova,ОФИС ВАРНА,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026,NaN,NaN
3,Vesela Nikolova,ОФИС ВАРНА,2026-01-29,Варна-Шабла-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026,NaN,NaN
4,Vesela Nikolova,ОФИС ВАРНА,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,Vesela Nikolova,ОФИС ВАРНА,2026-08-28,Бяла-Варна-Добрич-Русе,3.0,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,NaN,NaN,470.0,32000,564.0,17.625000,28,8,2026,NaN,20000.0
304,Vesela Nikolova,ОФИС ВАРНА,2026-08-28,Бяла-Варна-Добрич-Тервел-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ВЕНЦИСЛАВ КРУМОВ,NaN,NaN,500.0,20000,550.0,27.500000,28,8,2026,NaN,7000.0
305,Vesela Nikolova,ОФИС ВАРНА,2026-08-31,Варна-НХК-Каварна-Добрич-Варна,6.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,NaN,NaN,500.0,32000,600.0,18.750000,28,8,2026,12000.0,16000.0
306,Vesela Nikolova,ОФИС ВАРНА,2026-08-31,Русе-Тервел-Нова Камена - Гешаново-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,NaN,NaN,440.0,32000,528.0,16.500000,28,8,2026,NaN,32000.0
307,Vesela Nikolova,ОФИС ВАРНА,2026-08-31,НХК-Поморие,1.0,ДЪЛВАН ЕООД,ИВАН ГЕОРГИЕВ ТУРМАНОВ,А7660КР,NaN,NaN,8000,NaN,0.000000,31,8,2026,NaN,8000.0

In [6]:
cleaned_data.to_csv('transport_data.csv', index=False)

In [7]:
cleaned_data = pd.read_csv('transport_data.csv')
cleaned_data

,ТЪРГОВЕЦ,ВЪЗЛОЖИТЕЛ,КУРС_ДАТА,КУРС,БРОЙ_ОБЕКТИ,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА,ЛИТРИ_1,ЛИТРИ_2
0,Vesela Nikolova,ОФИС ВАРНА,2026-01-26,Русе-Тервел-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026,NaN,NaN
1,Vesela Nikolova,ОФИС ВАРНА,2026-01-27,Варна-Риш-Нефтохим,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026,NaN,NaN
2,Vesela Nikolova,ОФИС ВАРНА,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026,NaN,NaN
3,Vesela Nikolova,ОФИС ВАРНА,2026-01-29,Варна-Шабла-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026,NaN,NaN
4,Vesela Nikolova,ОФИС ВАРНА,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,Vesela Nikolova,ОФИС ВАРНА,2026-08-28,Бяла-Варна-Добрич-Русе,3.0,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,NaN,NaN,470.0,32000,564.0,17.625000,28,8,2026,NaN,20000.0
304,Vesela Nikolova,ОФИС ВАРНА,2026-08-28,Бяла-Варна-Добрич-Тервел-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ВЕНЦИСЛАВ КРУМОВ,NaN,NaN,500.0,20000,550.0,27.500000,28,8,2026,NaN,7000.0
305,Vesela Nikolova,ОФИС ВАРНА,2026-08-31,Варна-НХК-Каварна-Добрич-Варна,6.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,NaN,NaN,500.0,32000,600.0,18.750000,28,8,2026,12000.0,16000.0
306,Vesela Nikolova,ОФИС ВАРНА,2026-08-31,Русе-Тервел-Нова Камена - Гешаново-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ПАВЕЛ СТЕФАНОВ ГЕОРГИЕВ,NaN,NaN,440.0,32000,528.0,16.500000,28,8,2026,NaN,32000.0
307,Vesela Nikolova,ОФИС ВАРНА,2026-08-31,НХК-Поморие,1.0,ДЪЛВАН ЕООД,ИВАН ГЕОРГИЕВ ТУРМАНОВ,А7660КР,NaN,NaN,8000,NaN,0.000000,31,8,2026,NaN,8000.0

In [8]:
mean_km = round(cleaned_data['КМ'].mean(), 2)
mean_liters = round(cleaned_data['Л'].mean(), 2)
mean_price_total = round(cleaned_data['€_ЦЕНА_ОБЩО'].mean(), 2)
mean_price_per_1000 = round(cleaned_data['€_ЦЕНА_ЗА_1000'].mean(), 2)
mean_price_per_1000

np.float64(14.85)