In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from streamlit import columns
from sympy.assumptions.cnf import AND

In [10]:
data = pd.read_excel('transport_data.xlsx')
data

,ДАТА,КУРС_ДАТА,ВЪЗЛОЖИТЕЛ,КУРС,БРОЙ_ОБЕКТИ,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,...,ТОЛ_РАЗХОДИ,ЗАРЕДЕНО_ГОРИВО,ДРУГИ_РАЗХОДИ,СЪЗДАТЕЛ,СЪЗДАДЕНО_НА,ПРОМЯНА_ОТ,ПОСЛЕДЕН_ЪПДЕЙТ,ГОДИНА,МЕСЕЦ,ДЕН
0,20260127-0001,2026-01-26,ОФИС ВАРНА,Русе-Тервел-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 07:48:35.139,Plamen Svetoslavov,2026-04-01 18:48:15.743,2026,1,27
1,20260127-0002,2026-01-27,ОФИС ВАРНА,Варна-Риш-Нефтохим,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 16:36:41.699,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,27
2,20260127-0003,2026-01-28,ОФИС ВАРНА,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 16:39:22.266,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,27
3,20260128-0001,2026-01-29,ОФИС ВАРНА,Варна-Шабла-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-28 15:39:15.844,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,28
4,20260129-0001,2026-01-30,ОФИС ВАРНА,Варна-НХК-Повеляново-Добрич-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-29 11:09:16.459,Plamen Svetoslavov,2026-04-01 18:48:17.024,2026,1,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,20260928-0008,2026-09-29,ОФИС ВАРНА,Русе - Житница-Черна-Нова камена-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,NaN,400.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-09-28 17:02:19.471,Vesela Nikolova,2026-09-28 17:04:24.148,2026,9,28
366,20260928-0009,2026-09-29,ОФИС ВАРНА,Варна-Аспарухово-Хидро-Варна,1.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,200.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-09-28 17:04:28.472,Vesela Nikolova,2026-10-01 13:03:27.528,2026,9,28
367,20260928-0010,2026-09-29,ОФИС ВАРНА,Варна-Бяла-Блъсково-Варна,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,240.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-09-28 17:05:59.686,Vesela Nikolova,2026-10-01 13:03:34.837,2026,9,28
368,20260928-0011,2026-09-29,ОФИС ВАРНА,Ваарна-Аспарухово-Караманите-Добрич-Малина-Варна,5.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,300.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-09-28 17:07:53.157,Vesela Nikolova,2026-09-28 17:10:29.960,2026,9,28
369,20260928-0012,2026-09-30,ОФИС ВАРНА,Варна-НХК-Каварна-Добрич-Варна,3.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,480.0,...,NaN,NaN,NaN,Vesela Nikolova,2026-09-28 17:10:46.289,Vesela Nikolova,2026-09-28 17:12:39.859,2026,9,28

In [11]:
data.columns

Index(['ДАТА', 'КУРС_ДАТА', 'ВЪЗЛОЖИТЕЛ', 'КУРС', 'БРОЙ_ОБЕКТИ', 'ПРЕВОЗВАЧ',
       'ШОФЬОР', 'ВЛЕКАЧ', 'ЦИСТЕРНА', 'КМ', 'Л', '€_ЦЕНА_ОБЩО',
       '€_ЦЕНА_ЗА_1000', 'ЛИТРИ_1', 'СТАТУС_ФАКТУРА', 'ЛИТРИ_2', 'ТОЛ_РАЗХОДИ',
       'ЗАРЕДЕНО_ГОРИВО', 'ДРУГИ_РАЗХОДИ', 'СЪЗДАТЕЛ', 'СЪЗДАДЕНО_НА',
       'ПРОМЯНА_ОТ', 'ПОСЛЕДЕН_ЪПДЕЙТ', 'ГОДИНА', 'МЕСЕЦ', 'ДЕН'],
      dtype='object')

In [12]:
cleaned_data = data[['СЪЗДАТЕЛ', 'ВЪЗЛОЖИТЕЛ', 'КУРС_ДАТА', 'КУРС', 'БРОЙ_ОБЕКТИ', 'ПРЕВОЗВАЧ', 'ШОФЬОР', 'ВЛЕКАЧ', 'ЦИСТЕРНА', 'КМ', 'Л', '€_ЦЕНА_ОБЩО', '€_ЦЕНА_ЗА_1000', 'ДЕН', 'МЕСЕЦ', 'ГОДИНА', 'ЛИТРИ_1', 'ЛИТРИ_2']]
cleaned_data = cleaned_data.rename(columns={'СЪЗДАТЕЛ': 'ТЪРГОВЕЦ'})
cleaned_data

,ТЪРГОВЕЦ,ВЪЗЛОЖИТЕЛ,КУРС_ДАТА,КУРС,БРОЙ_ОБЕКТИ,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА,ЛИТРИ_1,ЛИТРИ_2
0,Vesela Nikolova,ОФИС ВАРНА,2026-01-26,Русе-Тервел-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026,NaN,NaN
1,Vesela Nikolova,ОФИС ВАРНА,2026-01-27,Варна-Риш-Нефтохим,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026,NaN,NaN
2,Vesela Nikolova,ОФИС ВАРНА,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026,NaN,NaN
3,Vesela Nikolova,ОФИС ВАРНА,2026-01-29,Варна-Шабла-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026,NaN,NaN
4,Vesela Nikolova,ОФИС ВАРНА,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Русе - Житница-Черна-Нова камена-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,NaN,400.0,32000,480.0,15.000000,28,9,2026,NaN,32000.0
366,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Варна-Аспарухово-Хидро-Варна,1.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,200.0,32000,240.0,7.500000,28,9,2026,NaN,32000.0
367,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Варна-Бяла-Блъсково-Варна,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,240.0,32000,288.0,9.000000,28,9,2026,NaN,32000.0
368,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Ваарна-Аспарухово-Караманите-Добрич-Малина-Варна,5.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,300.0,30000,360.0,12.000000,28,9,2026,NaN,9500.0
369,Vesela Nikolova,ОФИС ВАРНА,2026-09-30,Варна-НХК-Каварна-Добрич-Варна,3.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,480.0,32000,576.0,18.000000,28,9,2026,15000.0,15000.0

In [13]:
cleaned_data = cleaned_data[['ТЪРГОВЕЦ', 'ВЪЗЛОЖИТЕЛ', 'КУРС_ДАТА', 'КУРС', 'БРОЙ_ОБЕКТИ', 'ПРЕВОЗВАЧ', 'ШОФЬОР', 'ВЛЕКАЧ', 'ЦИСТЕРНА', 'КМ', 'Л', '€_ЦЕНА_ОБЩО', '€_ЦЕНА_ЗА_1000', 'ДЕН', 'МЕСЕЦ', 'ГОДИНА', 'ЛИТРИ_1', 'ЛИТРИ_2']]
cleaned_data = cleaned_data.rename(columns={'points_count': 'БРОЙ_ОБЕКТИ'})
cleaned_data

,ТЪРГОВЕЦ,ВЪЗЛОЖИТЕЛ,КУРС_ДАТА,КУРС,БРОЙ_ОБЕКТИ,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА,ЛИТРИ_1,ЛИТРИ_2
0,Vesela Nikolova,ОФИС ВАРНА,2026-01-26,Русе-Тервел-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026,NaN,NaN
1,Vesela Nikolova,ОФИС ВАРНА,2026-01-27,Варна-Риш-Нефтохим,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026,NaN,NaN
2,Vesela Nikolova,ОФИС ВАРНА,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026,NaN,NaN
3,Vesela Nikolova,ОФИС ВАРНА,2026-01-29,Варна-Шабла-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026,NaN,NaN
4,Vesela Nikolova,ОФИС ВАРНА,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Русе - Житница-Черна-Нова камена-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,NaN,400.0,32000,480.0,15.000000,28,9,2026,NaN,32000.0
366,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Варна-Аспарухово-Хидро-Варна,1.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,200.0,32000,240.0,7.500000,28,9,2026,NaN,32000.0
367,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Варна-Бяла-Блъсково-Варна,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,240.0,32000,288.0,9.000000,28,9,2026,NaN,32000.0
368,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Ваарна-Аспарухово-Караманите-Добрич-Малина-Варна,5.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,300.0,30000,360.0,12.000000,28,9,2026,NaN,9500.0
369,Vesela Nikolova,ОФИС ВАРНА,2026-09-30,Варна-НХК-Каварна-Добрич-Варна,3.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,480.0,32000,576.0,18.000000,28,9,2026,15000.0,15000.0

In [14]:
cleaned_data.to_csv('transport_data.csv', index=False)

In [15]:
cleaned_data = pd.read_csv('transport_data.csv')
cleaned_data

,ТЪРГОВЕЦ,ВЪЗЛОЖИТЕЛ,КУРС_ДАТА,КУРС,БРОЙ_ОБЕКТИ,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА,ЛИТРИ_1,ЛИТРИ_2
0,Vesela Nikolova,ОФИС ВАРНА,2026-01-26,Русе-Тервел-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026,NaN,NaN
1,Vesela Nikolova,ОФИС ВАРНА,2026-01-27,Варна-Риш-Нефтохим,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026,NaN,NaN
2,Vesela Nikolova,ОФИС ВАРНА,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026,NaN,NaN
3,Vesela Nikolova,ОФИС ВАРНА,2026-01-29,Варна-Шабла-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026,NaN,NaN
4,Vesela Nikolova,ОФИС ВАРНА,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Русе - Житница-Черна-Нова камена-Русе,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,NaN,400.0,32000,480.0,15.000000,28,9,2026,NaN,32000.0
366,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Варна-Аспарухово-Хидро-Варна,1.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,200.0,32000,240.0,7.500000,28,9,2026,NaN,32000.0
367,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Варна-Бяла-Блъсково-Варна,4.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,240.0,32000,288.0,9.000000,28,9,2026,NaN,32000.0
368,Vesela Nikolova,ОФИС ВАРНА,2026-09-29,Ваарна-Аспарухово-Караманите-Добрич-Малина-Варна,5.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,300.0,30000,360.0,12.000000,28,9,2026,NaN,9500.0
369,Vesela Nikolova,ОФИС ВАРНА,2026-09-30,Варна-НХК-Каварна-Добрич-Варна,3.0,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИВАНОВ СТОЯНОВ,CB2201CC,NaN,480.0,32000,576.0,18.000000,28,9,2026,15000.0,15000.0

In [16]:
mean_km = round(cleaned_data['КМ'].mean(), 2)
mean_liters = round(cleaned_data['Л'].mean(), 2)
mean_price_total = round(cleaned_data['€_ЦЕНА_ОБЩО'].mean(), 2)
mean_price_per_1000 = round(cleaned_data['€_ЦЕНА_ЗА_1000'].mean(), 2)
mean_price_per_1000

np.float64(14.69)