In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from streamlit import columns

In [6]:
data = pd.read_excel('transport_data.xlsx')
data

,ДАТА,КУРС_ДАТА,КУРС,МАРШРУТ_СНИМКА,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,...,ТОЛ_РАЗХОДИ,ЗАРЕДЕНО_ГОРИВО,ДРУГИ_РАЗХОДИ,СЪЗДАТЕЛ,СЪЗДАДЕНО_НА,ПРОМЯНА_ОТ,ПОСЛЕДЕН_ЪПДЕЙТ,ГОДИНА,МЕСЕЦ,ДЕН
0,20260127-0001,2026-01-26,Русе-Тервел-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 07:48:35.139,Plamen Svetoslavov,2026-02-26 12:03:29.540,2026,1,27
1,20260127-0002,2026-01-27,Варна-Риш-Нефтохим,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 16:36:41.699,Plamen Svetoslavov,2026-02-01 08:23:26.349,2026,1,27
2,20260127-0003,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-27 16:39:22.266,Vesela Nikolova,2026-01-27 16:41:33.200,2026,1,27
3,20260128-0001,2026-01-29,Варна-Шабла-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-28 15:39:15.844,Vesela Nikolova,2026-01-28 15:41:35.766,2026,1,28
4,20260129-0001,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,...,NaN,NaN,NaN,Vesela Nikolova,2026-01-29 11:09:16.459,Vesela Nikolova,2026-01-29 11:11:21.095,2026,1,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,20260327-0006,2026-03-27,Варна-Повеляново-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,60.0,11000,...,NaN,NaN,NaN,Vesela Nikolova,2026-03-27 09:41:17.036,Vesela Nikolova,2026-03-27 09:43:12.499,2026,3,27
77,20260330-0001,2026-03-30,Бяла-Вълчи дол-Ген. Киселово-Стожер-Добрич-Тер...,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,530.0,32000,...,NaN,NaN,NaN,Vesela Nikolova,2026-03-30 09:24:52.870,Vesela Nikolova,2026-03-30 09:27:41.051,2026,3,30
78,20260330-0002,2026-03-30,Варна-Бяла-Русе-Добрич-Каварна-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,580.0,30000,...,NaN,NaN,NaN,Vesela Nikolova,2026-03-30 09:27:45.625,Vesela Nikolova,2026-03-30 09:29:15.621,2026,3,30
79,20260330-0003,2026-03-31,Варна-Девня-Добрич-Варна,NaN,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,150.0,34000,...,NaN,NaN,NaN,Vesela Nikolova,2026-03-30 09:29:29.592,Vesela Nikolova,2026-03-30 09:32:22.022,2026,3,30
80,20260304-0010,2026-03-04,Варна-Сенокос-Варна,NaN,ТРАНС ОЙЛ ЕООД,ДИАН СТОЯНОВ АЛЕКСАНДРОВ,CB2201CC,P2849EE,160.0,18000,...,NaN,NaN,NaN,Vesela Nikolova,2026-03-31 15:05:16.166,Plamen Svetoslavov,2026-03-31 15:11:44.834,2026,3,4

In [12]:
cleaned_data = data[['СЪЗДАТЕЛ', 'КУРС_ДАТА', 'КУРС', 'ПРЕВОЗВАЧ', 'ШОФЬОР', 'ВЛЕКАЧ', 'ЦИСТЕРНА', 'КМ', 'Л', '€_ЦЕНА_ОБЩО', '€_ЦЕНА_ЗА_1000', 'ДЕН', 'МЕСЕЦ', 'ГОДИНА']]
cleaned_data = cleaned_data.rename(columns={'СЪЗДАТЕЛ': 'ТЪРГОВЕЦ'})
cleaned_data

,ТЪРГОВЕЦ,КУРС_ДАТА,КУРС,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА
0,Vesela Nikolova,2026-01-26,Русе-Тервел-Русе,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026
1,Vesela Nikolova,2026-01-27,Варна-Риш-Нефтохим,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026
2,Vesela Nikolova,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026
3,Vesela Nikolova,2026-01-29,Варна-Шабла-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026
4,Vesela Nikolova,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,Vesela Nikolova,2026-03-27,Варна-Повеляново-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,60.0,11000,60.0,5.454545,27,3,2026
77,Vesela Nikolova,2026-03-30,Бяла-Вълчи дол-Ген. Киселово-Стожер-Добрич-Тер...,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,530.0,32000,530.0,16.562500,30,3,2026
78,Vesela Nikolova,2026-03-30,Варна-Бяла-Русе-Добрич-Каварна-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,580.0,30000,580.0,19.333333,30,3,2026
79,Vesela Nikolova,2026-03-31,Варна-Девня-Добрич-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,150.0,34000,150.0,4.411765,30,3,2026
80,Vesela Nikolova,2026-03-04,Варна-Сенокос-Варна,ТРАНС ОЙЛ ЕООД,ДИАН СТОЯНОВ АЛЕКСАНДРОВ,CB2201CC,P2849EE,160.0,18000,143.0,7.944444,4,3,2026

In [29]:
cleaned_data.to_csv('transport_data.csv', index=False)

In [30]:
cleaned_data = pd.read_csv('transport_data.csv')
cleaned_data

,ТЪРГОВЕЦ,КУРС_ДАТА,КУРС,ПРЕВОЗВАЧ,ШОФЬОР,ВЛЕКАЧ,ЦИСТЕРНА,КМ,Л,€_ЦЕНА_ОБЩО,€_ЦЕНА_ЗА_1000,ДЕН,МЕСЕЦ,ГОДИНА
0,Vesela Nikolova,2026-01-26,Русе-Тервел-Русе,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,300.0,32000,285.0,8.906250,27,1,2026
1,Vesela Nikolova,2026-01-27,Варна-Риш-Нефтохим,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,250.0,19100,240.0,12.565445,27,1,2026
2,Vesela Nikolova,2026-01-28,Нефтохим-Варна-Добрич-Караплит-Подайва-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,420.0,31700,400.0,12.618297,27,1,2026
3,Vesela Nikolova,2026-01-29,Варна-Шабла-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,NaN,180.0,18000,153.0,8.500000,28,1,2026
4,Vesela Nikolova,2026-01-30,Варна-НХК-Повеляново-Добрич-Русе,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,560.0,30000,532.0,17.733333,29,1,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,Vesela Nikolova,2026-03-27,Варна-Повеляново-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,60.0,11000,60.0,5.454545,27,3,2026
77,Vesela Nikolova,2026-03-30,Бяла-Вълчи дол-Ген. Киселово-Стожер-Добрич-Тер...,ЕВРОУЕЙ СЪРВИЗ ООД,ДАНИЕЛ ПЕНЧЕВ ПЕНЧЕВ,Р7826КН,Р2530ЕЕ,530.0,32000,530.0,16.562500,30,3,2026
78,Vesela Nikolova,2026-03-30,Варна-Бяла-Русе-Добрич-Каварна-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,580.0,30000,580.0,19.333333,30,3,2026
79,Vesela Nikolova,2026-03-31,Варна-Девня-Добрич-Варна,ЕВРОУЕЙ СЪРВИЗ ООД,ГЕОРГИ ИЛИЕВ ГЕОРГИЕВ,Р9581МА,Р4961ЕЕ,150.0,34000,150.0,4.411765,30,3,2026
80,Vesela Nikolova,2026-03-04,Варна-Сенокос-Варна,ТРАНС ОЙЛ ЕООД,ДИАН СТОЯНОВ АЛЕКСАНДРОВ,CB2201CC,P2849EE,160.0,18000,143.0,7.944444,4,3,2026

In [31]:
mean_km = round(cleaned_data['КМ'].mean(), 2)
mean_liters = round(cleaned_data['Л'].mean(), 2)
mean_price_total = round(cleaned_data['€_ЦЕНА_ОБЩО'].mean(), 2)
mean_price_per_1000 = round(cleaned_data['€_ЦЕНА_ЗА_1000'].mean(), 2)
mean_price_per_1000

np.float64(12.71)